/*
 * This file is generated by jOOQ.
 */
package com.example.app.entity;


import com.example.app.entity.tables.TblUsers;


/**
 * Convenience access to all tables in user.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user.tbl_users</code>.
     */
    public static final TblUsers TBL_USERS = TblUsers.TBL_USERS;
}
