/*
 * This file is generated by jOOQ.
 */
package com.example.app.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String email;
    private String firstName;
    private String lastName;

    public TblUsers() {}

    public TblUsers(TblUsers value) {
        this.id = value.id;
        this.email = value.email;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
    }

    public TblUsers(
        Integer id,
        String email,
        String firstName,
        String lastName
    ) {
        this.id = id;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    /**
     * Getter for <code>user.tbl_users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>user.tbl_users.id</code>.
     */
    public TblUsers setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>user.tbl_users.email</code>.
     */
    public TblUsers setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>user.tbl_users.first_name</code>.
     */
    public TblUsers setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>user.tbl_users.last_name</code>.
     */
    public TblUsers setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TblUsers other = (TblUsers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblUsers (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);

        sb.append(")");
        return sb.toString();
    }
}
