/*
 * This file is generated by jOOQ.
 */
package com.example.app.entity.tables.records;


import com.example.app.entity.tables.TblUsers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUsersRecord extends UpdatableRecordImpl<TblUsersRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user.tbl_users.id</code>.
     */
    public TblUsersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user.tbl_users.email</code>.
     */
    public TblUsersRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.tbl_users.first_name</code>.
     */
    public TblUsersRecord setFirstName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.tbl_users.last_name</code>.
     */
    public TblUsersRecord setLastName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user.tbl_users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TblUsers.TBL_USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return TblUsers.TBL_USERS.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return TblUsers.TBL_USERS.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return TblUsers.TBL_USERS.LAST_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public TblUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TblUsersRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TblUsersRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public TblUsersRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public TblUsersRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblUsersRecord
     */
    public TblUsersRecord() {
        super(TblUsers.TBL_USERS);
    }

    /**
     * Create a detached, initialised TblUsersRecord
     */
    public TblUsersRecord(Integer id, String email, String firstName, String lastName) {
        super(TblUsers.TBL_USERS);

        setId(id);
        setEmail(email);
        setFirstName(firstName);
        setLastName(lastName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TblUsersRecord
     */
    public TblUsersRecord(com.example.app.entity.tables.pojos.TblUsers value) {
        super(TblUsers.TBL_USERS);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            resetChangedOnNotNull();
        }
    }
}
